import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "./components/ReactQueryProvider";
import { Toaster } from "sonner";
import { RoleProvider } from "./(panle)/context/RoleContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      
      <body className={`antialiased h-[100dvh] w-full`}>
        <ReactQueryProvider  >
          <RoleProvider> {children}</RoleProvider>
        </ReactQueryProvider>
        <Toaster />
      <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/7/langs/fa.js"></script>
      <link rel="manifest" href="/manifest.json" />
      </body>
    </html>
  );
}
